// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1uV_lcQPuKBCmSyq4S6GkdankefTVs3c',
    appId: '1:554538066049:web:369c6ba01ecc460526ad80',
    messagingSenderId: '554538066049',
    projectId: 'sign-in-881f1',
    authDomain: 'sign-in-881f1.firebaseapp.com',
    storageBucket: 'sign-in-881f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0a9iPnwc8z6pwVTEZdFuh66BTsABpx8E',
    appId: '1:554538066049:android:62f8241bf47174b126ad80',
    messagingSenderId: '554538066049',
    projectId: 'sign-in-881f1',
    storageBucket: 'sign-in-881f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg2fXjsFAaI2-D9BglvWcq3LJsj6N0O1Y',
    appId: '1:554538066049:ios:dcf7d1015b5eebd726ad80',
    messagingSenderId: '554538066049',
    projectId: 'sign-in-881f1',
    storageBucket: 'sign-in-881f1.appspot.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1uV_lcQPuKBCmSyq4S6GkdankefTVs3c',
    appId: '1:554538066049:web:801fd59d306fda8326ad80',
    messagingSenderId: '554538066049',
    projectId: 'sign-in-881f1',
    authDomain: 'sign-in-881f1.firebaseapp.com',
    storageBucket: 'sign-in-881f1.appspot.com',
  );
}
